name: pixorama_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  serverpod_client:
    path: ../vendor/serverpod/packages/serverpod_client
